Adds mutation for editing post
Saturnd-Earth/se-be pull request #18
Opened 2021-01-07 15:37 UTC by drewwilliams5280

Minor edit for adding mutation.

2021-01-07 16:00 UTC, moosehandlr commented on spec/graphql/mutations/posts/edit_post_spec.rb
> +          require 'pry'; binding.pry
Looks like a pry was left behind here.

2021-01-07 16:02 UTC, moosehandlr requested changes
Looks good! There was a just a pry left behind in your test do thats why the CI wont build.

2021-01-08 16:42 UTC, ggerdsen commented
> Looks good! There was a just a pry left behind in your test do thats why the CI wont build.

Good catch!

2021-01-11 17:31 UTC, moosehandlr commented
Looks great!

2021-01-11 17:32 UTC, moosehandlr approved these changes

2021-01-11 17:32 UTC, merged